name: Test the project

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      # Setup environment
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: node index.js
